apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakUserCredential
metadata:
  name: example-user-password
  namespace: default
spec:
  userRef:
    name: example-user
  userSecret:
    secretName: example-user-credentials
    create: true
    usernameKey: username
    passwordKey: password
    passwordPolicy:
      length: 24
